import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./dashboard/ui/navbar/page";
import Side from "./dashboard/ui/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        <div className="flex">
          <div className="  md:block h-[100vh] w-[330px] ">
            <Side />
          </div>
          <div className="p-5 w-full md:max-w-[1140px]"> {children}</div>
        </div>
      </body>
    </html>
  );
}
